### ISSUE TITLE
Please use new field/metabox API in your registration output

### ISSUE THREAD

**Issue by jtsternberg** [hasinhayder/cmb2-metabox-generator#5]
this generator is pretty awesome! It's using the deprecated filter though, so can you please update to use the new API. It is demonstrated in the [example-functions.php](https://github.com/WebDevStudios/CMB2/blob/master/example-functions.php) file. Related: https://github.com/WebDevStudios/CMB2/issues/397

**Comment by ediamin** [comment]
@jtsternberg I'm working on it. Will submit the pull request in a day or two. :)

**Comment by hasinhayder** [comment]
thanks @ediamin. looking forward to it

**Comment by hasinhayder** [comment]
@jtsternberg  it is now done. Thanks goes to @ediamin  for his fantastic pull request.

**Comment by jtsternberg** [comment]
Nice! :thumbsup:

**Comment by hasinhayder** [comment]
@jtsternberg can we request to you to add this generator's link in the official CMB2 wiki? Might be helpful to a lot of people out there. Thanks in advance :)

**Comment by jtsternberg** [comment]
Yes, I'll do!

**Comment by jtsternberg** [comment]
Added! https://github.com/WebDevStudios/CMB2/commit/62fba947e25916d19b94a71e2d4d8eee0e9e975a
